#!/usr/bin/env bash
set -e

docker compose \
  --project-name pomelo \
  --env-file .env \
  -f docker/app/docker-compose.dev.yaml \
  -f docker/judge0/docker-compose.yaml \
  --project-directory . \
  up --build --watch
